package lib

import (
	"fmt"
	"net/http"
	"strings"
)

type Fingerprint struct {
	Name       string
	Detected   bool
	Evidence   string
	Confidence string
}

var wafSignatures = map[string]struct {
	Headers      map[string]string
	BodyContains []string
	Cookies      []string
}{
	"Cloudflare": {
		Headers: map[string]string{
			"Server":          "cloudflare",
			"CF-RAY":          "",
			"CF-Cache-Status": "",
			"cf-ray":          "",
		},
		BodyContains: []string{
			"Attention Required! | Cloudflare",
			"cloudflare",
			"__cfduid",
		},
		Cookies: []string{"__cfduid", "_cfuvid"},
	},
	"Akamai": {
		Headers: map[string]string{
			"Server":               "AkamaiGHost",
			"X-Akamai-Request-ID":  "",
			"X-Akamai_transformed": "",
		},
		BodyContains: []string{
			"Akamai",
			"Reference #",
		},
		Cookies: []string{},
	},
	"AWS CloudFront": {
		Headers: map[string]string{
			"Server":       "CloudFront",
			"X-Amz-Cf-Id":  "",
			"X-Amz-Cf-Pop": "",
		},
		BodyContains: []string{},
		Cookies:      []string{},
	},
	"Azure Application Gateway": {
		Headers: map[string]string{
			"Server":           "Microsoft-Azure-Application-Gateway",
			"X-MS-RequestID":   "",
			"X-AspNet-Version": "",
		},
		BodyContains: []string{},
		Cookies:      []string{},
	},
	"F5 BIG-IP": {
		Headers: map[string]string{
			"Server":       "BigIP",
			"X-F5-Auth-Tm": "",
			"Content-Type": "text/vnd.tmplusad",
		},
		BodyContains: []string{
			"BIG-IP",
			"F5 Networks",
			"TMO",
		},
		Cookies: []string{"TIN", "LastMRH_SESSION"},
	},
	"Fortinet FortiGate": {
		Headers: map[string]string{
			"Server":    "FortiGate",
			"Fortigate": "",
		},
		BodyContains: []string{
			"FortiGate",
			"fortinet",
		},
		Cookies: []string{"e8cf2e20bb0c8e6d6e19"},
	},
	"Sucuri": {
		Headers: map[string]string{
			"Server":      "Sucuri/Cloudproxy",
			"X-Sucuri-":   "",
			"X-Sucuri-ID": "",
		},
		BodyContains: []string{
			"Sucuri",
			"sucuri",
			"CloudProxy",
		},
		Cookies: []string{},
	},
	"Imperva Incapsula": {
		Headers: map[string]string{
			"Server":  "Imperva",
			"X-CDN":   "Incapsula",
			"X-Iinfo": "",
		},
		BodyContains: []string{
			"Incapsula",
			"imperva",
			"_incapsula_",
		},
		Cookies: []string{"incap_ses", "visid_incap"},
	},
	"ModSecurity": {
		Headers: map[string]string{
			"Server":      "ModSecurity",
			"ModSecurity": "",
		},
		BodyContains: []string{
			"ModSecurity",
			"mod_security",
			"This error was generated by ModSecurity",
		},
		Cookies: []string{},
	},
	"OpenResty": {
		Headers: map[string]string{
			"Server":       "openresty",
			"X-Powered-By": "OpenResty",
		},
		BodyContains: []string{},
		Cookies:      []string{},
	},
	"Nginx": {
		Headers: map[string]string{
			"Server": "nginx",
		},
		BodyContains: []string{},
		Cookies:      []string{},
	},
	"Apache": {
		Headers: map[string]string{
			"Server": "apache",
		},
		BodyContains: []string{},
		Cookies:      []string{},
	},
	"IIS": {
		Headers: map[string]string{
			"Server":       "microsoft-iis",
			"X-Powered-By": "ASP.NET",
		},
		BodyContains: []string{},
		Cookies:      []string{},
	},
	"Spring Boot": {
		Headers: map[string]string{
			"X-Application": "Spring",
			"Content-Type":  "application/vnd.spring-boot",
		},
		BodyContains: []string{},
		Cookies:      []string{"JSESSIONID"},
	},
	"Shiro": {
		Headers: map[string]string{},
		BodyContains: []string{
			"shiro",
			"rememberMe",
			"DeleteMe",
		},
		Cookies: []string{"rememberMe", "JSESSIONID"},
	},
}

func DetectFingerprint(resp *http.Response, body []byte) []Fingerprint {
	var results []Fingerprint

	headers := make(map[string]string)
	for k, v := range resp.Header {
		if len(v) > 0 {
			headers[strings.ToLower(k)] = v[0]
		}
	}

	bodyLower := strings.ToLower(string(body))

	for name, sig := range wafSignatures {
		score := 0
		evidence := ""

		for header, pattern := range sig.Headers {
			if val, ok := headers[strings.ToLower(header)]; ok {
				if pattern == "" || strings.Contains(strings.ToLower(val), strings.ToLower(pattern)) {
					score += 3
					evidence += fmt.Sprintf("Header[%s=%s] ", header, val)
				}
			}
		}

		for _, pattern := range sig.BodyContains {
			if strings.Contains(bodyLower, strings.ToLower(pattern)) {
				score += 2
				evidence += fmt.Sprintf("Body[%s] ", pattern)
			}
		}

		for _, cookie := range sig.Cookies {
			if strings.Contains(bodyLower, strings.ToLower(cookie)) {
				score += 1
				evidence += fmt.Sprintf("Cookie[%s] ", cookie)
			}
		}

		if score > 0 {
			confidence := "low"
			if score >= 5 {
				confidence = "high"
			} else if score >= 3 {
				confidence = "medium"
			}

			results = append(results, Fingerprint{
				Name:       name,
				Detected:   true,
				Evidence:   evidence,
				Confidence: confidence,
			})
		}
	}

	return results
}

func PrintFingerprintReport(targetURL string, resp *http.Response, body []byte) {
	fmt.Println()
	fmt.Println(CyanStyle("┌──────────────────────────────────────────────────────────────────────┐"))
	fmt.Println(CyanStyle("│] WAF/CDN/中间件指纹识别报告                                        │"))
	fmt.Println(CyanStyle("└──────────────────────────────────────────────────────────────────────┘"))
	fmt.Println()

	fingerprints := DetectFingerprint(resp, body)

	if len(fingerprints) == 0 {
		fmt.Printf("  %s[*] 未检测到已知WAF/CDN指纹%s\n", YellowStyle(""), ResetStyle())
	} else {
		fmt.Printf("  %s[+] 检测到 %d 个可能的指纹:%s\n", GreenStyle(""), len(fingerprints), ResetStyle())
		for _, fp := range fingerprints {
			if fp.Confidence == "high" {
				fmt.Printf("\n  [%s] %s (置信度: %s)\n", fp.Name, GreenStyle("高"), fp.Confidence)
			} else if fp.Confidence == "medium" {
				fmt.Printf("\n  [%s] %s (置信度: %s)\n", fp.Name, YellowStyle("中"), fp.Confidence)
			} else {
				fmt.Printf("\n  [%s] %s (置信度: %s)\n", fp.Name, RedStyle("低"), fp.Confidence)
			}
			fmt.Printf("     证据: %s\n", fp.Evidence)
		}
	}

	if resp != nil {
		fmt.Printf("\n  响应头信息:\n")
		fmt.Printf("    Status: %d\n", resp.StatusCode)
		for k, v := range resp.Header {
			if len(v) > 0 {
				fmt.Printf("    %s: %s\n", k, v[0])
			}
		}
	}

	fmt.Println()
	fmt.Println(CyanStyle("└──────────────────────────────────────────────────────────────────────┘"))
}
